project_id = "okspcuzngoublrmtjreh"

[functions.create-default-users]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.transcribe-youtube]
verify_jwt = true

[functions.scheduled-cleanup]
verify_jwt = false

[functions.monitor-transcription-errors]
verify_jwt = false

[functions.get-youtube-audio-url]
verify_jwt = true